version: "3.9"

services:
  db:
    image: postgres:16
    container_name: movies_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres/database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
      - movies-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [
              "CMD-SHELL",
              "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: movies_es
    restart: always
    env_file:
      - .env
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://es:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - movies-es-data:/usr/share/elasticsearch/data

  etl:
    build: ./etl
    container_name: movies_etl
    restart: always
    env_file:
      - .env
    environment:
      ES_HOST: es
      ES_PORT: 9200
      ES_INDEX: ${ES_INDEX}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS}
      STORAGE_FILE_NAME: ${STORAGE_FILE_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      db:
        condition: service_healthy
      es:
        condition: service_healthy
    volumes:
      - movies-etl-state:/data

  cache:
    image: redis:5.0.4
    container_name: movies_cache
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [
        "CMD-SHELL",
        "redis-cli ping | grep PONG"
      ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  api:
    build: ./backend
    container_name: movies_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      es:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  movies-postgres-data:
  movies-es-data:
  movies-etl-state:
